# Dockerfile.dev

FROM node:18-alpine

# Optional: Needed for file watching in Alpine
RUN apk add --no-cache bash

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]
